#############################################################################
# Makefile for building: imatch
# Generated by qmake (3.0) (Qt 5.4.1)
# Project:  IMATCH.pro
# Template: app
# Command: /opt/Qt5.4.1/5.4/gcc_64/bin/qmake -spec linux-g++ CONFIG+=debug -o Makefile IMATCH.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I. -I/usr/local/include -I/opt/Qt5.4.1/5.4/gcc_64/include -I/opt/Qt5.4.1/5.4/gcc_64/include/QtCore -I. -I/opt/Qt5.4.1/5.4/gcc_64/mkspecs/linux-g++
QMAKE         = /opt/Qt5.4.1/5.4/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = imatch1.0.0
DISTDIR = /home/kevin/Desktop/IMATCH/.tmp/imatch1.0.0
LINK          = g++
LFLAGS        = -Wl,-rpath,/opt/Qt5.4.1/5.4/gcc_64 -Wl,-rpath,/opt/Qt5.4.1/5.4/gcc_64/lib
LIBS          = $(SUBLIBS) -L/usr/local/lib -lopencv_features2d -lopencv_calib3d -lopencv_contrib -lopencv_core -lopencv_flann -lopencv_gpu -lopencv_ml -lopencv_imgproc -lopencv_video -lopencv_legacy -lopencv_highgui -lopencv_stitching -lopencv_photo -lopencv_ocl -lopencv_videostab -lopencv_superres -lopencv_nonfree -lX11 -L/opt/Qt5.4.1/5.4/gcc_64/lib -lQt5Core -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		ncc.cpp \
		match.cpp \
		delaunay.cpp \
		feature.cpp \
		utils.cpp 
OBJECTS       = main.o \
		ncc.o \
		match.o \
		delaunay.o \
		feature.o \
		utils.o
DIST          = /opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/spec_pre.prf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/common/shell-unix.conf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/common/unix.conf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/common/linux.conf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/common/gcc-base.conf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/common/g++-base.conf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/common/g++-unix.conf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/qconfig.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/qt_functions.prf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/qt_config.prf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/linux-g++/qmake.conf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/spec_post.prf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/exclusive_builds.prf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/default_pre.prf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/resolve_config.prf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/default_post.prf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/warn_on.prf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/qt.prf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/resources.prf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/moc.prf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/unix/thread.prf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/testcase_targets.prf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/exceptions.prf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/yacc.prf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/lex.prf \
		IMATCH.pro ncc.h \
		match.h \
		delaunay.h \
		feature.h \
		utils.h main.cpp \
		ncc.cpp \
		match.cpp \
		delaunay.cpp \
		feature.cpp \
		utils.cpp
QMAKE_TARGET  = imatch
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = imatch


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: IMATCH.pro /opt/Qt5.4.1/5.4/gcc_64/mkspecs/linux-g++/qmake.conf /opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/spec_pre.prf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/common/shell-unix.conf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/common/unix.conf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/common/linux.conf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/common/gcc-base.conf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/common/g++-base.conf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/common/g++-unix.conf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/qconfig.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/qt_functions.prf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/qt_config.prf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/linux-g++/qmake.conf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/spec_post.prf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/exclusive_builds.prf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/default_pre.prf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/resolve_config.prf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/default_post.prf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/warn_on.prf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/qt.prf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/resources.prf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/moc.prf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/unix/thread.prf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/testcase_targets.prf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/exceptions.prf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/yacc.prf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/lex.prf \
		IMATCH.pro \
		/opt/Qt5.4.1/5.4/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -spec linux-g++ CONFIG+=debug -o Makefile IMATCH.pro
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/spec_pre.prf:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/common/shell-unix.conf:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/common/unix.conf:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/common/linux.conf:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/common/gcc-base.conf:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/common/gcc-base-unix.conf:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/common/g++-base.conf:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/common/g++-unix.conf:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/qconfig.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_core.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_designer.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_enginio.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_gui.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_help.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_location.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_network.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_qml.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_quick.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_script.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_sql.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_svg.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webview.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_xml.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/qt_functions.prf:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/qt_config.prf:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/linux-g++/qmake.conf:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/spec_post.prf:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/exclusive_builds.prf:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/default_pre.prf:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/resolve_config.prf:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/default_post.prf:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/warn_on.prf:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/qt.prf:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/resources.prf:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/moc.prf:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/unix/thread.prf:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/testcase_targets.prf:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/exceptions.prf:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/yacc.prf:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/lex.prf:
IMATCH.pro:
/opt/Qt5.4.1/5.4/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ CONFIG+=debug -o Makefile IMATCH.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ncc.h match.h delaunay.h feature.h utils.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp ncc.cpp match.cpp delaunay.cpp feature.cpp utils.cpp $(DISTDIR)/


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp utils.h \
		/usr/local/include/opencv2/opencv.hpp \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/core.hpp \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/flann/miniflann.hpp \
		/usr/local/include/opencv2/flann/defines.h \
		/usr/local/include/opencv2/flann/config.h \
		/usr/local/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/imgproc/imgproc.hpp \
		/usr/local/include/opencv2/photo/photo.hpp \
		/usr/local/include/opencv2/photo/photo_c.h \
		/usr/local/include/opencv2/video/video.hpp \
		/usr/local/include/opencv2/video/tracking.hpp \
		/usr/local/include/opencv2/video/background_segm.hpp \
		/usr/local/include/opencv2/features2d/features2d.hpp \
		/usr/local/include/opencv2/objdetect/objdetect.hpp \
		/usr/local/include/opencv2/calib3d/calib3d.hpp \
		/usr/local/include/opencv2/ml/ml.hpp \
		/usr/local/include/opencv2/highgui/highgui_c.h \
		/usr/local/include/opencv2/highgui/highgui.hpp \
		/usr/local/include/opencv2/contrib/contrib.hpp \
		/usr/local/include/opencv2/contrib/retina.hpp \
		/usr/local/include/opencv2/contrib/openfabmap.hpp \
		match.h \
		ncc.h \
		feature.h \
		delaunay.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

ncc.o: ncc.cpp ncc.h \
		utils.h \
		/usr/local/include/opencv2/opencv.hpp \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/core.hpp \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/flann/miniflann.hpp \
		/usr/local/include/opencv2/flann/defines.h \
		/usr/local/include/opencv2/flann/config.h \
		/usr/local/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/imgproc/imgproc.hpp \
		/usr/local/include/opencv2/photo/photo.hpp \
		/usr/local/include/opencv2/photo/photo_c.h \
		/usr/local/include/opencv2/video/video.hpp \
		/usr/local/include/opencv2/video/tracking.hpp \
		/usr/local/include/opencv2/video/background_segm.hpp \
		/usr/local/include/opencv2/features2d/features2d.hpp \
		/usr/local/include/opencv2/objdetect/objdetect.hpp \
		/usr/local/include/opencv2/calib3d/calib3d.hpp \
		/usr/local/include/opencv2/ml/ml.hpp \
		/usr/local/include/opencv2/highgui/highgui_c.h \
		/usr/local/include/opencv2/highgui/highgui.hpp \
		/usr/local/include/opencv2/contrib/contrib.hpp \
		/usr/local/include/opencv2/contrib/retina.hpp \
		/usr/local/include/opencv2/contrib/openfabmap.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ncc.o ncc.cpp

match.o: match.cpp match.h \
		utils.h \
		/usr/local/include/opencv2/opencv.hpp \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/core.hpp \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/flann/miniflann.hpp \
		/usr/local/include/opencv2/flann/defines.h \
		/usr/local/include/opencv2/flann/config.h \
		/usr/local/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/imgproc/imgproc.hpp \
		/usr/local/include/opencv2/photo/photo.hpp \
		/usr/local/include/opencv2/photo/photo_c.h \
		/usr/local/include/opencv2/video/video.hpp \
		/usr/local/include/opencv2/video/tracking.hpp \
		/usr/local/include/opencv2/video/background_segm.hpp \
		/usr/local/include/opencv2/features2d/features2d.hpp \
		/usr/local/include/opencv2/objdetect/objdetect.hpp \
		/usr/local/include/opencv2/calib3d/calib3d.hpp \
		/usr/local/include/opencv2/ml/ml.hpp \
		/usr/local/include/opencv2/highgui/highgui_c.h \
		/usr/local/include/opencv2/highgui/highgui.hpp \
		/usr/local/include/opencv2/contrib/contrib.hpp \
		/usr/local/include/opencv2/contrib/retina.hpp \
		/usr/local/include/opencv2/contrib/openfabmap.hpp \
		ncc.h \
		feature.h \
		delaunay.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o match.o match.cpp

delaunay.o: delaunay.cpp delaunay.h \
		utils.h \
		/usr/local/include/opencv2/opencv.hpp \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/core.hpp \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/flann/miniflann.hpp \
		/usr/local/include/opencv2/flann/defines.h \
		/usr/local/include/opencv2/flann/config.h \
		/usr/local/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/imgproc/imgproc.hpp \
		/usr/local/include/opencv2/photo/photo.hpp \
		/usr/local/include/opencv2/photo/photo_c.h \
		/usr/local/include/opencv2/video/video.hpp \
		/usr/local/include/opencv2/video/tracking.hpp \
		/usr/local/include/opencv2/video/background_segm.hpp \
		/usr/local/include/opencv2/features2d/features2d.hpp \
		/usr/local/include/opencv2/objdetect/objdetect.hpp \
		/usr/local/include/opencv2/calib3d/calib3d.hpp \
		/usr/local/include/opencv2/ml/ml.hpp \
		/usr/local/include/opencv2/highgui/highgui_c.h \
		/usr/local/include/opencv2/highgui/highgui.hpp \
		/usr/local/include/opencv2/contrib/contrib.hpp \
		/usr/local/include/opencv2/contrib/retina.hpp \
		/usr/local/include/opencv2/contrib/openfabmap.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o delaunay.o delaunay.cpp

feature.o: feature.cpp feature.h \
		utils.h \
		/usr/local/include/opencv2/opencv.hpp \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/core.hpp \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/flann/miniflann.hpp \
		/usr/local/include/opencv2/flann/defines.h \
		/usr/local/include/opencv2/flann/config.h \
		/usr/local/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/imgproc/imgproc.hpp \
		/usr/local/include/opencv2/photo/photo.hpp \
		/usr/local/include/opencv2/photo/photo_c.h \
		/usr/local/include/opencv2/video/video.hpp \
		/usr/local/include/opencv2/video/tracking.hpp \
		/usr/local/include/opencv2/video/background_segm.hpp \
		/usr/local/include/opencv2/features2d/features2d.hpp \
		/usr/local/include/opencv2/objdetect/objdetect.hpp \
		/usr/local/include/opencv2/calib3d/calib3d.hpp \
		/usr/local/include/opencv2/ml/ml.hpp \
		/usr/local/include/opencv2/highgui/highgui_c.h \
		/usr/local/include/opencv2/highgui/highgui.hpp \
		/usr/local/include/opencv2/contrib/contrib.hpp \
		/usr/local/include/opencv2/contrib/retina.hpp \
		/usr/local/include/opencv2/contrib/openfabmap.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o feature.o feature.cpp

utils.o: utils.cpp utils.h \
		/usr/local/include/opencv2/opencv.hpp \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/core.hpp \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/flann/miniflann.hpp \
		/usr/local/include/opencv2/flann/defines.h \
		/usr/local/include/opencv2/flann/config.h \
		/usr/local/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/imgproc/imgproc.hpp \
		/usr/local/include/opencv2/photo/photo.hpp \
		/usr/local/include/opencv2/photo/photo_c.h \
		/usr/local/include/opencv2/video/video.hpp \
		/usr/local/include/opencv2/video/tracking.hpp \
		/usr/local/include/opencv2/video/background_segm.hpp \
		/usr/local/include/opencv2/features2d/features2d.hpp \
		/usr/local/include/opencv2/objdetect/objdetect.hpp \
		/usr/local/include/opencv2/calib3d/calib3d.hpp \
		/usr/local/include/opencv2/ml/ml.hpp \
		/usr/local/include/opencv2/highgui/highgui_c.h \
		/usr/local/include/opencv2/highgui/highgui.hpp \
		/usr/local/include/opencv2/contrib/contrib.hpp \
		/usr/local/include/opencv2/contrib/retina.hpp \
		/usr/local/include/opencv2/contrib/openfabmap.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o utils.o utils.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

